comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    require_base: no        # [yes :: must have a base report to post]
    require_head: yes       # [yes :: must have a head report to post]
    branches:               # branch names that can post comment
        - "master"
ignore:
    - "uli_init/tests"
    - "uli_init/compounds"
    - "uli_init/forcefields"
    - "uli_init/trajectories"
    - "uli_init/logs"
    - "uli_init/__version__.py"
    - "Notebooks"
    - "setup.py"

