name: polybinder 
channels:
  - conda-forge
dependencies:
  - foyer=0.11.3
  - freud=2.12.1
  - gsd=2.7.0
  - mbuild=0.15.1
  - pip=22.0.4
  - pytest
  - pytest-cov
  - python=3.9
  - scipy=1.9.3
  - signac=1.7.0
  - signac-flow=0.18.1
  - pip:
      - git+https://github.com/chrisjonesBSU/polybinderCG.git@main
      - git+https://github.com/cmelab/cmeutils.git@master
