name: uli-init
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - foyer=0.9.2
  - gsd=2.4.0
  - hoomd=2.9.4
  - mbuild=0.12.0
  - numpy=1.20.1
  - pip=21.0
  - pytest
  - pytest-cov
  - python=3.7
  - scipy=1.6.0
  - signac=1.6.0
  - signac-flow=0.12.0
  - pip:
      - git+https://github.com/cmelab/uli-init.git@0.2.1
