name: uli
channels:
  - conda-forge
  - omnia
dependencies:
  - python=3.7
  - pip
  - mbuild 
  - foyer
  - numpy
  - scipy
  - matplotlib
  - gsd
  - py3dmol
  - deepsmiles
  - signac
  - signac-flow
  - pytest
  - mdanalysis
  - networkx
  - tqdm
  - json
