name: uli-test
channels:
  - conda-forge
  - omnia
  - mosdef
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - mbuild
  - hoomd
  - openbabel
  - foyer
  - gsd
  - py3dmol
  - deepsmiles

