name: uli-init
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - foyer=0.9.4
  - freud=2.7.0
  - gsd=2.4.0
  - hoomd=2.9.6=gpu_py39he2a7f1f_1
  - mbuild=0.13.1
  - numpy=1.20.1
  - pip=21.0
  - pytest
  - pytest-cov
  - python=3.9
  - scipy=1.6.0
  - signac=1.6.0
  - signac-flow=0.12.0
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/chrisjonesBSU/paek_cg.git@main
      - git+https://github.com/cmelab/uli-init.git@0.3.0
