name: uli-dev
channels:
  - conda-forge
  - omnia
  - mosdef
dependencies:
  - python=3.7
  - pip
  - numpy
  - packmol
  - parmed
  - mdtraj
  - lark-parser
  - lxml
  - openmm 
  - networkx
  - scipy
  - signac
  - signac-flow
  - oset
  - requests
  - garnett
  - matplotlib
  - openbabel
  - gsd
  - py3dmol
  - deepsmiles
  - ele
