name: uli
channels:
  - conda-forge
  - omnia
dependencies:
  - python=3.7
  - pip=19.3
  - mbuild 
  - foyer
  - numpy
  - scipy
  - matplotlib
  - gsd
  - py3dmol
  - deepsmiles
  - signac
  - signac-flow
  - pip:
    - "--editable=git+git@github.com:rsdefever/GAFF-foyer.git#egg=GAFF-foyer-master"
