name: uli-dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - ele
  - hoomd=2.9.4
  - garnett
  - gsd
  - mdtraj
  - networkx
  - openbabel
  - oset
  - packmol
  - parmed
  - scipy
  - foyer
  - numpy
  - scipy
  - matplotlib
  - gsd
  - py3dmol
  - deepsmiles
  - signac
  - signac-flow
  - pytest
  - pip:
      - git+https://github.com/chrisjonesBSU/mbuild.git@hoomd_sim
